import os

structure = {
    "app/api": [
        "__init__.py",
        "main.py"
    ],
    "app/api/routes": [
        "__init__.py",
        "restaurants.py",
        "reservations.py",
        "customers.py",
        "notifications.py"
    ],
    "app/api/utils": [
        "__init__.py",
        "email_service.py",
        "slot_manager.py"
    ]
}

for folder, files in structure.items():
    os.makedirs(folder, exist_ok=True)
    for file in files:
        file_path = os.path.join(folder, file)
        if not os.path.exists(file_path):
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(f"# {file} — autogenerated\n")
print("API folder structure created successfully!")
